### ISSUE TITLE
failed to install tables

### ISSUE THREAD

**Issue by Tongzhao9417** [waltervanheuven/psychopy-on-M1#5]
Well, I failed to install psychopy on m1. There are some errors and confusion during the process.

1. I failed to install tables whe use ``pip install tables`` the error as following:
```Collecting tables
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library not found for -llzo2
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -llzo
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      def _dump_h5_backtrace():
          cdef object bt = []
      
          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------
      
      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14)
      * Found cython 3.0.0
      * USE_PKGCONFIG: True
      * Found conda env: ``/Users/tongzhao/miniconda3``
      * Found HDF5 headers at ``/opt/homebrew/opt/hdf5/include``, library at ``/opt/homebrew/opt/hdf5/lib``.
      .. WARNING:: Could not find the HDF5 runtime.
         The HDF5 shared library was *not* found in the default library
         paths. In case of runtime problems, please remember to install it.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Found bzip2 headers at ``/opt/homebrew/opt/bzip2/include``, library at ``/opt/homebrew/opt/bzip2/lib``.
      * pkg-config header dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.4/include
      * pkg-config library dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.4/lib
      * Found blosc headers at ``/opt/homebrew/Cellar/c-blosc/1.21.4/include``, library at ``/opt/homebrew/Cellar/c-blosc/1.21.4/lib``.
      .. WARNING:: Could not find the blosc runtime.
         The blosc shared library was *not* found in the default library
         paths. In case of runtime problems, please remember to install it.
      * Found blosc2 headers at ``/private/var/folders/b9/smm3d4xj4y778d4gpcc3xvjc0000gn/T/pip-build-env-n4a_qy9x/overlay/include``, library at ``/private/var/folders/b9/smm3d4xj4y778d4gpcc3xvjc0000gn/T/pip-build-env-n4a_qy9x/overlay/lib``.
        * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/Users/tongzhao/Documents/Psychopy/psychopy-on-M1/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/tongzhao/Documents/Psychopy/psychopy-on-M1/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/tongzhao/Documents/Psychopy/psychopy-on-M1/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/b9/smm3d4xj4y778d4gpcc3xvjc0000gn/T/pip-build-env-n4a_qy9x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/b9/smm3d4xj4y778d4gpcc3xvjc0000gn/T/pip-build-env-n4a_qy9x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/b9/smm3d4xj4y778d4gpcc3xvjc0000gn/T/pip-build-env-n4a_qy9x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/b9/smm3d4xj4y778d4gpcc3xvjc0000gn/T/pip-build-env-n4a_qy9x/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/b9/smm3d4xj4y778d4gpcc3xvjc0000gn/T/pip-build-env-n4a_qy9x/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I guess there might need some skills to install tables.

2. some confuse about step 7
as the instroduction said, i need to `cd tmp` to install Psychtoolbox. Do you mean that I need to go into the tmp folder under the root directory of the computer? In other words, is it /tmp?

BTW, the installation of Psychtoolbox also failed. I don't know if it's because of an error in the tables installation.

3. some mistake in step 11
after modify setup.cfg, we should also modify the setup.py as replacing pyqt5 with pyqt6. another issue also mentioned this problem.

**Comment by waltervanheuven** [comment]
To install tables use:

```sh
pip install git+https://github.com/PyTables/PyTables
```

`tmp` directory should be in the main folder.

Instructions have been updated for PsychoPy 2023.2.0.

**Comment by Tongzhao9417** [comment]
> To install tables use:
> 
> ```shell
> pip install git+https://github.com/PyTables/PyTables
> ```
> 
> `tmp` directory should be in the main folder.
> 
> Instructions have been updated for PsychoPy 2023.2.0.

Hey, thanks for you reply. The table issues solved, but there are some new issues. 

1. The step 12, Install pyo. Do you mean ```pip install psychopy-pyo```?

2. There are some error when I want to run psychopy in step 13, error info in belowing:
```
Traceback (most recent call last):
  File "/Users/tongzhao/miniconda3/bin/psychopy", line 33, in <module>
    sys.exit(load_entry_point('PsychoPy==2023.1.3', 'gui_scripts', 'psychopy')())
  File "/Users/tongzhao/miniconda3/bin/psychopy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/tongzhao/miniconda3/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Users/tongzhao/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/PsychoPy-2023.1.3-py3.9.egg/psychopy/__init__.py", line 44, in <module>
    from psychopy.preferences import prefs
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/PsychoPy-2023.1.3-py3.9.egg/psychopy/preferences/__init__.py", line 13, in <module>
    from . import preferences as prefsLib
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/PsychoPy-2023.1.3-py3.9.egg/psychopy/preferences/preferences.py", line 11, in <module>
    from pkg_resources import parse_version
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/tongzhao/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyobjc<8.0' distribution was not found and is required by PsychoPy
```

It sounds like a problem with pyobjc, but when i try to install it using pip, it tells me that it's already installed.

**Comment by Tongzhao9417** [comment]
update: there are also some issues when i install psychtoolbox, that are some error info:
```
Installed /Users/tongzhao/miniconda3/lib/python3.9/site-packages/psychtoolbox-3.0.19.3-py3.9-macosx-11.0-arm64.egg
Processing dependencies for psychtoolbox==3.0.19.3
Searching for psychtoolbox==3.0.19.3
Reading https://pypi.org/simple/psychtoolbox/
No local packages or working download links found for psychtoolbox==3.0.19.3
error: Could not find suitable distribution for Requirement.parse('psychtoolbox==3.0.19.3')
```
when i check the url ```https://pypi.org/simple/psychtoolbox/```, the lastest wheel is 3.0.19.0 not 3.0.19.3. Is it possible due to this problem?

**Comment by Tongzhao9417** [comment]
Update2: My bad, the default version of my laptop is Python 3.9 and this is the reason I failed to compile. I switch the version of python to 3.10 and all problem has sovled. Thanks for you job! The native Psychopy is so swift!
